services:
  backend:
    image: retrolad7/mediatron-service:${IMAGE_TAG:-latest}
    container_name: mediatron-service
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      OAUTH2_GOOGLE_CLIENT: ${OAUTH2_GOOGLE_CLIENT}
      OAUTH2_GOOGLE_SECRET: ${OAUTH2_GOOGLE_SECRET}
      FRONTEND_URL: ${FRONTEND_HOST}:${FRONTEND_PORT}
      SPRING_APPLICATION_PROFILE: ${SPRING_APPLICATION_PROFILE}
      TELEGRAM_CLIENT_SECRET: ${TELEGRAM_CLIENT_SECRET}
      LOGSTASH_URL: ${LOGSTASH_URL}
#      SERVER_FORWARD_HEADERS_STRATEGY: framework
    ports:
      - "8080:8080"
    networks:
      - mediatron-net
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: mediatron
    ports:
      - "5433:5432"
    networks:
      - mediatron-net
    volumes:
      - mediatron-vol:/var/lib/postgresql/data
  front:
    image: retrolad7/mediatron-front:${IMAGE_TAG:-latest}
    container_name: mediatron-front
    restart: always
    environment:
      BACKEND_HOST: ${BACKEND_HOST:-localhost}
      BACKEND_PORT: ${BACKEND_PORT:-8080}
      FRONTEND_PORT: ${FRONTEND_PORT:-80}
    ports:
      - "${FRONTEND_PORT:-80}:80"
    networks:
      - mediatron-net
    volumes:
      - ./config/nginx/default.conf.template:/etc/nginx/templates/default.conf.template
  bot:
    image: retrolad7/mediatron-bot
    container_name: mediatron-bot
    restart: always
    environment:
      BACKEND_HOST: ${BACKEND_HOST:-localhost}
      BACKEND_PORT: ${BACKEND_PORT:-8080}
      TELEGRAM_API_TOKEN: ${TELEGRAM_API_TOKEN}
      REST_CLIENT_ID: ${REST_CLIENT_ID}
      REST_CLIENT_SECRET: ${REST_CLIENT_SECRET}
      SPRING_APPLICATION_PROFILE: ${SPRING_APPLICATION_PROFILE}
      LOGSTASH_URL: ${LOGSTASH_URL}
    networks:
      - mediatron-net
networks:
  mediatron-net:

volumes:
  mediatron-vol:
