services:
  backend:
    image: retrolad7/mediatron-service:${IMAGE_TAG:-latest}
    container_name: mediatron-service
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      OAUTH2_GOOGLE_CLIENT: ${OAUTH2_GOOGLE_CLIENT}
      OAUTH2_GOOGLE_SECRET: ${OAUTH2_GOOGLE_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}:${FRONTEND_PORT}
      SPRING_APPLICATION_PROFILE: ${SPRING_APPLICATION_PROFILE}
#      SERVER_FORWARD_HEADERS_STRATEGY: framework
    networks:
      - mediatron-net
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: mediatron
    ports:
      - "5433:5432"
    networks:
      - mediatron-net
    volumes:
      - mediatron-vol:/var/lib/postgresql/data
  front:
    image: retrolad7/mediatron-front:${IMAGE_TAG:-latest}
    container_name: mediatron-front
    restart: always
    ports:
      - "${FRONTEND_PORT:-80}:80"
    networks:
      - mediatron-net

networks:
  mediatron-net:

volumes:
  mediatron-vol:
