spring:
  application:
    name: mediatron-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/mediatron
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT}
            client-secret: ${OAUTH2_GOOGLE_SECRET}
  profiles:
    active: ${SPRING_APPLICATION_PROFILE:dev}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    parameters:
      duplicate-file-mode: WARN

app:
  front:
    url: ${FRONTEND_URL:http://localhost:5173}
  images:
    base-dir: images
    tmdb-images-url: https://image.tmdb.org/t/p/original
  lang:
    default: ru
  logging:
    path: ${user.home}/mediatron/logs/mediatron-service

logstash:
  url: ${LOGSTASH_URL}

server:
  # Включает поддержку заголовков X-Forwarded-*
  forward-headers-strategy: framework

trusted-clients:
  clients:
    telegram-bot:
      client_id: telegram-bot
      client_secret: ${TELEGRAM_CLIENT_SECRET}
      client_authority: CLIENT

management:
  sampling:
    probability: 1
  tracing:
    propagation:
      type: w3c