spring:
  application:
    name: mediatron
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mediatron
    username: mt_user
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  thymeleaf:
    cache: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

app:
  images:
    base-dir: images
    posters-dir: ${app.images.base-dir}/poster
    backdrop-dir: ${app.images.base-dir}/backdrop
    logos-dir: ${app.images.base-dir}/logo
    tmdb-images-url: https://image.tmdb.org/t/p/original
    tmdb-profile-icon: https://www.themoviedb.org/assets/2/v4/glyphicons/basic/glyphicons-basic-4-user-grey-d8fe957375e70239d6abdd549fd7568c89281b2179b5f4470e2e12895792dfa5.svg
  lang:
    default: ru