spring:
  application:
    name: mediatron
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mediatron
    username: mt_user
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1095820494475-49tddgkumsfitjj2b69ab1cd9vu9ipb6.apps.googleusercontent.com
            client-secret: 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

  thymeleaf:
    cache: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
logging:
  level:
    org.springframework.security: TRACE

    # Уровень DEBUG покажет параметры, подставляемые вместо '?'
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.stat: debug

    # Также полезно для общего дебага Hibernate
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE # Для новых версий Hibernate

app:
  jwt:
    secret: app.jwt.secret=ZGhpYXNkZmdoamtsMTIzNDU2Nzg5MHF3ZXJ0eXVpb3Bhc2RmZ2g=
  images:
    base-dir: images
    tmdb-images-url: https://image.tmdb.org/t/p/original
  lang:
    default: ru
server:
  address: 0.0.0.0