spring:
  application:
    name: mediatron-telegram-bot
  main:
    web-application-type: none
bot:
  name: mediatron_bot
  token: ${TELEGRAM_API_TOKEN}
mediatron:
  url: http://${BACKEND_HOST:-localhost}:${BACKEND_PORT:-8080}
logging:
  level:
    web: DEBUG